Productos:
    type: entity
    table: productos
    indexes:
        fk_productos:
            columns:
                - categoria_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        precio:
            type: decimal
            nullable: true
            precision: 2
            scale: 0
        stock:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    manyToOne:
        categoria:
            targetEntity: Categorias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
